django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('grappelli', include('grappelli.urls')),
    
    path('admin/', admin.site.urls),

    path('register/', user_views.register, name='register'),

    path('profile/', user_views.profile, name='profile'),
    
    path('profile/delete/', user_views.deleteuser, name='profile-delete'),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
    path('', include('recepti.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recepti/urls.py
from django.urls import path
from .views import (

    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    UserFavoriteListView,
    CommentCreateView,
    CommentDeleteView,
    CommentUpdateView,
    CategoryPredjeloListView,
    CategoryGlavnoListView,
    CategoryDesertListView,
    LikeView,
    DislikeView,

)
from . import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .models import Post, Comment

urlpatterns = [

    path('', PostListView.as_view(), name='recepti-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('user/<str:username>/favoriti', UserFavoriteListView.as_view(), name='user-favorite'),
    path('posts/predjela', CategoryPredjeloListView.as_view(), name='category-predjelo'),
    path('posts/glavna', CategoryGlavnoListView.as_view(), name='category-glavno'),
    path('posts/deserti', CategoryDesertListView.as_view(), name='category-desert'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='post-comment'),
    path('post/comment/<int:pk>/delete', CommentDeleteView.as_view(), name='post-comment-delete'),
    path('post/comment/<int:pk>/update', CommentUpdateView.as_view(), name='post-comment-update'),
    path('post/<int:pk>/like', LikeView.as_view(), name= 'post-like'),
    path('post/<int:pk>/dislike', DislikeView.as_view(), name= 'post-dislike'),
    path('about/', views.about, name='recepti-about')
]

recepti/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from PIL import Image
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from vote.models import VoteModel


# Create your models here.
 
#SQL modeli
class Post(VoteModel,models.Model):

    kategorije = [
        ('pr','predjelo'),
        ('gl','glavno jelo'),
        ('de','desert'),
    ]

    naslov = models.CharField(max_length=100)
    sazetak = models.TextField(max_length=200, default='Super recept! Usudi se probati...')
    sadrzaj = models.TextField()
    slika = models.ImageField(default='default_pict.jpg', upload_to='post_pics')
    date_posted = models.DateTimeField(default=timezone.now)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    kategorija = models.CharField(max_length=2, choices=kategorije, default = 'gl')
   
    def __str__(self):
        return self.naslov

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


    def save(self, *args, **kwargs):
        super(VoteModel,self).save(*args, **kwargs)

        img = Image.open(self.slika.path)

        if img.height > 640 or img.width > 320:
            output_size = (640, 320)
            img.thumbnail(output_size)
            img.save(self.slika.path)
       


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
   

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def __str__(self):
        return 'Komentar korisnika {}: {}'.format(self.user, self.content)
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.post.pk})

recepti/views.py
import json
from django.http import HttpResponse
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import (

    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView

)

from .models import Post, Comment 
from .filters import PostFilter

def home(request):
    postovi=Post.objects.all()
    search=request.GET('search')
    if search !='' and search is not None:
        postovi=postovi.Postfilter(naslov__icontains=search)

        context={
            'posts': postovi
        }
    else:
    
        context = {
            'posts': Post.objects.all()
        }
    return render(request, 'recepti/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'recepti/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 12

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        return context

class UserPostListView(ListView):
    model = Post
    template_name = 'recepti/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'

    paginate_by = 12

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(autor=user).order_by('-date_posted')

class UserFavoriteListView(ListView):
    model = Post
    template_name = 'recepti/category_favorite.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    success_url = '/'

    paginate_by = 12

    def get_queryset(self):
        posts = Post.objects.all()
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        liked_posts = []
        for post in posts:
            ids = post.votes.user_ids()
            for id,time in ids:
                if id == user.id:
                    liked_posts.append(post)
        return liked_posts

class CategoryPredjeloListView(ListView):
    model = Post
    template_name = 'recepti/category_predjelo.html'
    context_object_name = 'category-predjelo'
    paginate_by = 12
    

    def get_context_data(self, **kwargs):
        context = {
            'posts': Post.objects.all()
        }
        return context

class CategoryGlavnoListView(ListView):
    model = Post
    template_name = 'recepti/category_glavno.html'
    context_object_name = 'category-glavno'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = {
            'posts': Post.objects.all()
        }
        return context

class CategoryDesertListView(ListView):
    model = Post
    template_name = 'recepti/category_desert.html'
    context_object_name = 'category-desert'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = {
            'posts': Post.objects.all()
        }
        return context


class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['naslov','kategorija', 'sazetak', 'sadrzaj', 'slika']

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['naslov','kategorija', 'sazetak', 'sadrzaj', 'slika']

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.autor:
            return True
        return False

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['content']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.user:
            return True
        return False

class LikeView(LoginRequiredMixin,UpdateView):
    model = Post
    fields = []
    template_name = 'recepti/like_form.html'
    context_object_name = 'post-like'
    

    def form_valid(self, form):
        post = Post.objects.get(pk=self.kwargs.get('pk'))
        success_url = '/post/'+ str(self.kwargs.get('pk'))
        user_id = self.request.user.id
        if not post.votes.exists(user_id):
            post.votes.up(user_id)
        return super().form_valid(form)

class DislikeView(LoginRequiredMixin,UpdateView):
    model = Post
    fields = []
    context_object_name = 'post-dislike'
    template_name = 'recepti/dislike_form.html'
    
    def form_valid(self, form):
        post = Post.objects.get(pk=self.kwargs.get('pk'))
        success_url = '/post/'+ str(self.kwargs.get('pk'))
        user_id = self.request.user.id
        
        post.votes.down(user_id)
        return super().form_valid(form)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.autor:
            return True
        return False

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    success_url = '/'

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.user or self.request.user == comment.post.autor:
            return True
        return False

def about(request):
    return render(request, 'recepti/about.html', {'title': 'O nama'})

recepti/templates/recepti/about.html
{% extends "recepti/base.html" %}

{% block content %}

    <main role="main" class="container">
        <article class="media content-section">
            <div class="media-body">
            <h1>O nama</h1>
            <p class="article-content">
                Prirodoslovno-matematički fakultet u Splitu<br>
                Preddiplomski studij Informatika<br>
                Uvod u programsko inženjerstvo<br>
                A.Budic, J.Juricic<br>
                2019/2020.
            </p>
            </div>
        </article>
    </main>
    
{% endblock content %}

recepti/templates/recepti/base.html
{% load static %}
{%  load bootstrap %}

<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" type="text/css" href="{% static 'recepti/main.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Baskervville&display=swap" rel="stylesheet">

  {% if title %}
  <title>Recepti-{{ title }}</title>
    {% else %}
        <title>Recepti</title>
    {% endif %}
</head>
<body>
  <Style type='text/css' >body{background-color:rgb(0,0,0);background-image:url(http://www.zingerbugimages.com/backgrounds/white_marble_background_seamless.jpg);background-position:top left;background-repeat:repeat;background-attachment:fixed;}</Style>
        <header class="site-header">
                <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                  <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'recepti-home' %}"><i class="fa fa-cutlery" aria-hidden="true"></i> Recepti</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
          
                    <div class="collapse navbar-collapse" id="navbarToggle">
                      <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'recepti-home' %}"><i class="fa fa-home" aria-hidden="true"></i> Naslovna</a>
                        <a class="nav-item nav-link" href="{% url 'recepti-about' %}">O nama</a>
                        
                       
                      </div>
          
                      <!-- Navbar Right Side -->
                      <div class="navbar-nav">
                        {% if user.is_authenticated %}
                          <a class="nav-item nav-link" href="{% url 'post-create' %}">Novi post</a>
                          <a class="nav-item nav-link" href="{% url 'user-posts' user.username %}">Moji recepti</a>
                          <a class="nav-item nav-link" href="{% url 'user-favorite' user.username %}">Moji favoriti</a>
                          <a class="nav-item nav-link" href="{% url 'profile' %}"><i class="fa fa-user" aria-hidden="true"></i> {{ user }}</a>
                          <a class="nav-item nav-link" href="{% url 'logout' %}">Odjavi se</a>
                        {% else %}
                          <a class="nav-item nav-link" href="{% url 'login' %}">Prijavi se</a>
                          <a class="nav-item nav-link" href="{% url 'register' %}">Registriraj se</a>
          
                        {% endif %}
                      </div>
                    </div>         
                  </div>         
                </nav>         
              </header>

              <main role="main" class="container">
                 
                    
                        {% if messages %}
                          {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                              {{ message }}
                            </div>
                          {% endfor %}
                        {% endif %}

                        <div class="content-section">
                          <h3>Pretraživanje</h3>
                          <p class='text-muted'> Unesite pojam
                            <div class="searchBox">
                              <form>
                                <input type="search" placeholder="Search" name="search" id="search">
                              </form>
                            </div>
                          </p>
                          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'category-predjelo' %}">Predjela</a>
                          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'category-glavno' %}">Glavna jela</a>
                          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'category-desert'  %}">Deserti</a>

                        </div>

                        <div class="w3-row-padding">
                        {% block content %}{% endblock %}
                        </div>

                    
                        
                      
                 
                  </main>
                  <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

recepti/templates/recepti/category_desert.html
{% extends "recepti/base.html" %}
{% block content %}

    <h4 class="mb-3">Deserti:</h4>
   

    {% for post in posts %}
        {% if post.get_kategorija_display == 'desert' %}
        <div class="w3-third">
            <a href="{% url 'post-detail' post.id %}" class="article-title"> <img src="{{ post.slika.url }}" style="width: 100%;"> </a>
                    <h5><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.naslov }}</a></h5>
        
            </div>
        {%  endif %}
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">Prva</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prethodna</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Sljedeća</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Posljednja</a>
      {% endif %}

    {% endif %}
    
    {% endblock content %}

recepti/templates/recepti/category_favorite.html
{% extends "recepti/base.html" %}
{% block content %}

    <h4 class="mb-3">Favoriti:</h4>
  
        {% for post in posts %}
        <div class="w3-third">
            <a href="{% url 'post-detail' post.id %}" class="article-title"> <img src="{{ post.slika.url }}" style="width: 100%;"> </a>
                    <h5><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.naslov }}</a></h5>
            </div>
        {% endfor %}



    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">Prva</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prethodna</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Sljedeća</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Posljednja</a>
      {% endif %}

    {% endif %}
    
    {% endblock content %}

recepti/templates/recepti/category_glavno.html
{% extends "recepti/base.html" %}
{% block content %}

    <h4 class="mb-3">Glavna jela:</h4>
   

    {% for post in posts %}
        {% if post.get_kategorija_display == 'glavno jelo' %}
        <div class="w3-third">
          <a href="{% url 'post-detail' post.id %}" class="article-title"> <img src="{{ post.slika.url }}" style="width: 100%;"> </a>
                  <h5><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.naslov }}</a></h5>
      
          </div>
        {%  endif %}
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">Prva</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prethodna</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Sljedeća</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Posljednja</a>
      {% endif %}

    {% endif %}
    
    {% endblock content %}

recepti/templates/recepti/category_predjelo.html
{% extends "recepti/base.html" %}
{%  load bootstrap %}
{% block content %}

    <h4 class="mb-3">Predjela:</h4>
   

    {% for post in posts %}
    {% if post.get_kategorija_display == 'predjelo' %}
   
    <div class="w3-third">
        <a href="{% url 'post-detail' post.id %}" class="article-title"> <img src="{{ post.slika.url }}" style="width: 100%;"> </a>
                <h5><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.naslov }}</a></h5>
    
        </div>
    {% endif %}
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">Prva</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prethodna</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Sljedeća</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Posljednja</a>
      {% endif %}

    {% endif %}
    
    {% endblock content %}

recepti/templates/recepti/comment_confirm_delete.html
{% extends "recepti/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Obriši komentar</legend>
                <h2>Jeste li sigurni da želite obrisati komentar: "{{ object.content }}" korisnika "{{ object.user }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" href="{% url 'post-detail' object.post.pk %}" type="submit">Da, obriši</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.post.pk %}">Odustani</a>
            </div>
        </form>
    </div>
{% endblock content %}

recepti/templates/recepti/comment_form.html
{% extends "recepti/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Novi komentar</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-secondary" type="submit">Objavi</button>
        </div>
    </form>
</div>
{% endblock content %}

recepti/templates/recepti/dislike_form.html
{% extends "recepti/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Kliknite Dislike ako želite ukloniti ovaj recept iz kategorije Favorita</legend>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-outline-secondary" type="submit">Dislike</button>
            </div>
        </fieldset>
        
    </form>
</div>
{% endblock content %}

recepti/templates/recepti/home.html
{% extends "recepti/base.html" %}
{%  load bootstrap %}
{% block content %}



    {% for post in posts %}
    <div class="w3-third">
    <a href="{% url 'post-detail' post.id %}" class="article-title"> <img src="{{ post.slika.url }}" style="width: 100%;"> </a>
            <h5><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.naslov }}</a></h5>

    </div>
    {% endfor %}
    {% if is_paginated %}
  <div class="w3-row-padding w3-center">
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-secondary mb-4" href="?page=1">Prva</a>
        <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.previous_page_number }}">Prethodna</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.next_page_number }}">Sljedeća</a>
        <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Posljednja</a>
      {% endif %}
    </div>

    {% endif %}
{% endblock content %}

recepti/templates/recepti/like_form.html
{% extends "recepti/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Kliknite Like ako želite dodati ovaj recept u kategoriju Favorita</legend>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-outline-secondary" type="submit">Like</button>
            </div>
        </fieldset>
        
    </form>
</div>
{% endblock content %}

recepti/templates/recepti/post_confirm_delete.html
{% extends "recepti/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Obriši objavu</legend>
                <h2>Jeste li sigurni da želite obrisati objavu "{{ object.naslov }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Da, Obriši</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Odustani</a>
            </div>
        </form>
    </div>
{% endblock content %}